/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/SAHA.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/SAHA.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tripo_node_84c3140c-dfae-439e-828e-c866df76f5c2'].geometry} material={materials['tripo_material_84c3140c-dfae-439e-828e-c866df76f5c2']} />
    </group>
  )
}

useGLTF.preload('/SAHA.glb')
